### ISSUE TITLE
Android Nougat / 7.0 

### ISSUE THREAD

**Issue by gsantner** [james34602/JamesDSPManager#2]
Hi there, 
will there be also an Android Nougat release?

BTW: Flashed the original DSP-Manager on my N-device, and it works flawlessly.

**Comment by james34602** [comment]
Yes, will be supported.
I'm looking the API issue :)

**Comment by BenBaltz** [comment]
Do you need a Nougat device to test on?

**Comment by james34602** [comment]
I don't have real Nougat to test, but Nougat version have been build, ready for test.

**Comment by BenBaltz** [comment]
If you can post it here, I have a 6P running Nougat.

**Comment by james34602** [comment]
Nice👍

**Comment by james34602** [comment]
https://drive.google.com/open?id=0B5xvL_71lUP_NldQWUlpUHBYeGs
Test for Nougat, nothing changed, only recompile

**Comment by gsantner** [comment]
@james34602 Can it also be compiled against `arm64` or  will the arm version also work?

**Comment by james34602** [comment]
Well, I will compile that, but in most case arm64 seems cannot work properly.

**Comment by james34602** [comment]
I'm finding new ways to perform sound processing without root your device, that is integrate some stuff in a media player app, it is working, what media player is my development target? May be I will release when completely done.
Because somehow one day, the root app may come extremely unstable, so I decide to slow the root app development.

**Comment by james34602** [comment]
I have release latest test on any version, there have two different library for Nougat, but they are functionally same.
https://github.com/james34602/JamesDSPManager/releases

**Comment by gsantner** [comment]
@james34602 thanks!
