### ISSUE TITLE
No source for 2.0?

### ISSUE THREAD

**Issue by magicgoose** [james34602/JamesDSPManager#23]
> Latest commit 33c9fff on Nov 29, 2018

I'm not sure maybe I should look somewhere else?

**Comment by james34602** [comment]
The native code of JamesDSP_Free is not available, but you can ask the processing principle by email.

**Comment by Jman420** [comment]
Who would the 'processing principle' be and how would we find out their email in order to contact them?  It is very unclear why this open source project seems to have been abandoned in favor of a closed source one, or if this project is still being maintained in parallel to a closed source one.

It also makes it very difficult, if not impossible, for the community to provide support or contributions with the current setup of open & closed source repos.

**Comment by james34602** [comment]
Email show up in my Github profile.
I don't see anyone so far interested at maintaining the core algorithm.
And, people should have no difficult at maintaining the GUI of the program, most people are just interested only the GUI(Translation, style) part.

**Comment by Jman420** [comment]
@james34602 I am interested in partnering and contributing to the backend and will reach out to you privately via email.
