### ISSUE TITLE
no .nomedia under /sdcard/JamesDSP/Convolver

### ISSUE THREAD

**Issue by githammerer** [james34602/JamesDSPManager#30]
Causes the .wav files to show under music players.

**Comment by james34602** [comment]
What's this?
Are this easy fix so that user can do it themself?

**Comment by robcore** [comment]
Either users can just create a blank ".nomedia" in the folder, it could be included in the installer, or (the least convenient option) created by the app.

I think the first two are reasonable, the last one more effort than it's worth.

**Comment by james34602** [comment]
@githammerer @robcore Got that, thanks.
I'm not active Android user, too many stuffs I don't know.

I think creating an empty file using the installer is simpler, I talk to installer maker to apply you guys request.
I'm not involved in the Magick installer, that's why I have to call someone to help.
